/*=============================================================================
	DiffusionFilter.usf: Post Tonemapper Diffusion Filter
=============================================================================*/

#include "/Engine/Private/Common.ush"
#include "/Engine/Private/ScreenPass.ush"
#include "/Engine/Private/PostProcessCommon.ush"

#define BLEND_MODE_LIGHTEN 0
#define BLEND_MODE_SCREEN 1
#define BLEND_MODE_OVERLAY 2
#define BLEND_MODE_HARDLIGHT 3
#define BLEND_MODE_SOFTLIGHT 4
#define BLEND_MODE_PREVIEW 5

SCREEN_PASS_TEXTURE_VIEWPORT(Input)
SCREEN_PASS_TEXTURE_VIEWPORT(Output)

float LuminanceMin;
float InvLuminanceWidth;
float BlendAmount;

Texture2D<float4> SceneColorTexture;
Texture2D<float4> BlurredColorTexture;
RWTexture2D<float4> OutMaskTexture;

//
// Generate Mask
//

int2 ClampToViewport(int2 PixelPos)
{
    return clamp(PixelPos, (int2) Input_ViewportMin, (int2) Input_ViewportMax - 1);
}

float3 GatherSceneColor(int2 PixelPos)
{
    int2 SrcPixelPos = (int2) Input_ViewportMin + DOWNSAMPLE_FACTOR * PixelPos;
    int2 LeftTop = ClampToViewport(SrcPixelPos - DOWNSAMPLE_FACTOR / 2);
    int2 RightBottom = ClampToViewport(SrcPixelPos + DOWNSAMPLE_FACTOR / 2);
    
    float3 Color = (float3) 0;
    
    for(int y = LeftTop.y; y <= RightBottom.y; ++y)
    {
        for(int x = LeftTop.x; x <= RightBottom.x; ++x) 
        {
            Color += SceneColorTexture[int2(x, y)].rgb;
        }
    }
    
    return Color / ((RightBottom.x - LeftTop.x + 1) * (RightBottom.y - LeftTop.y + 1));
}

[numthreads(8,8,1)]
void GenerateMaskCS(uint2 Id: SV_DispatchThreadID)
{
    int2 PixelPos = Id;

    if (all(PixelPos < Output_Extent))
    {
        float3 Color = GatherSceneColor(PixelPos);
        float Alpha = saturate((Luminance(Color) - LuminanceMin) * InvLuminanceWidth);

        OutMaskTexture[PixelPos] = float4(Color, Alpha);
    }
}

//
// Composite
//

float3 BlendLighten(float3 Base, float3 Blend)
{
    return max(Base, Blend);
}

float3 BlendScreen(float3 Base, float3 Blend)
{
    return 1.0 - (1.0 - Base) * (1.0 - Blend);
}

float3 BlendOverlay(float3 Base, float3 Blend)
{
    float3 A = 2.0 * Base * Blend;
    float3 B = 1.0 - 2.0 * (1.0 - Base) * (1.0 - Blend);
    return float3(
        Base.r < 0.5 ? A.r : B.r,
        Base.g < 0.5 ? A.g : B.g,
        Base.b < 0.5 ? A.b : B.b);
}

float3 BlendHardLight(float3 Base, float3 Blend)
{
    float3 A = 2.0 * Base * Blend;
    float3 B = 1.0 - 2.0 * (1.0 - Base) * (1.0 - Blend);
    return float3(
        Blend.r < 0.5 ? A.r : B.r,
        Blend.g < 0.5 ? A.g : B.g,
        Blend.b < 0.5 ? A.b : B.b);
}

float3 BlendSoftLight(float3 Base, float3 Blend)
{
    return (1.0 - 2.0 * Blend) * Base * Base + 2.0 * Blend * Base;
}

void CompositePS(float4 SvPosition : SV_Position, out float4 OutColor : SV_Target0)
{
    const float2 BufferUV = SvPositionToBufferUV(SvPosition);
    float3 SceneColor = Texture2DSampleLevel(SceneColorTexture, GlobalBilinearClampedSampler, BufferUV, 0).rgb;
    
    const float2 ViewportUV = (SvPosition.xy - Output_ViewportMin) * Output_ViewportSizeInverse;
    float4 BlurredColor = Texture2DSampleLevel(BlurredColorTexture, GlobalBilinearClampedSampler, ViewportUV, 0);
    
#if BLEND_MODE == BLEND_MODE_LIGHTEN
    float3 BlendedColor = BlendLighten(SceneColor, BlurredColor.rgb);
#elif BLEND_MODE == BLEND_MODE_SCREEN
    float3 BlendedColor = BlendScreen(SceneColor, BlurredColor.rgb);
#elif BLEND_MODE == BLEND_MODE_OVERLAY
    float3 BlendedColor = BlendOverlay(SceneColor, BlurredColor.rgb);
#elif BLEND_MODE == BLEND_MODE_HARDLIGHT
    float3 BlendedColor = BlendSoftLight(SceneColor, BlurredColor.rgb);
#elif BLEND_MODE == BLEND_MODE_HARDLIGHT
    float3 BlendedColor = BlendHardsLight(SceneColor, BlurredColor.rgb);
#elif BLEND_MODE == BLEND_MODE_SOFTLIGHT
    float3 BlendedColor = BlendSoftLight(SceneColor, BlurredColor.rgb);
#elif BLEND_MODE == BLEND_MODE_PREVIEW
    float3 BlendedColor = BlurredColor.a * BlurredColor.rgb;
    BlurredColor.a = 1.f;
#endif

    float Alpha = BlendAmount * BlurredColor.a;
    OutColor = float4(lerp(SceneColor, BlendedColor, Alpha), 0);
}
