/*=============================================================================
	PostProcessLine.usf: PostProcessing Line
=============================================================================*/

#include "/Engine/Private/Common.ush"
#include "/Engine/Private/ScreenPass.ush"
#include "/Engine/Private/DeferredShadingCommon.ush"
#include "/Engine/Private/PostProcessCommon.ush"
#include "/Engine/Private/ColorSpace.ush"

#define TARGET_TYPE_COLOR 0
#define TARGET_TYPE_NORMAL 1
#define FILTER_METHOD_CLASSIC_KUWAHARA 0
#define FILTER_METHOD_GENERALIZED_KUWAHARA 1
#define FILTER_METHOD_ANISOTROPIC_KUWAHARA 2
#define FILTER_METHOD_SYMMETRIC_NEAREST_NEIGHBOR 3
#define ORIENTTATION_COLOR 0
#define ORIENTTATION_DEPTH 1

SCREEN_PASS_TEXTURE_VIEWPORT(Input)

int FilterSize;

Texture2D InputTexture;
Texture2D OrientationTexture;

int2 ClampToViewport(int2 PixelPos)
{
    return clamp(PixelPos, (int2) Input_ViewportMin, (int2) Input_ViewportMax - 1);
}

float3 SampleColor(int2 PixelPos)
{
    return InputTexture[PixelPos].xyz;
}

float4 SampleNormal(int2 PixelPos)
{
    float3 Normal = InputTexture[PixelPos].xyz;
    return any(Normal) ? float4(2.0 * Normal - 1.0, 1.0) : float4(0, 0, 0, 0);
}

float4 ComputeColorMeanAndVariance(int2 LeftTop, int2 RightBottom)
{
    float4 Accum = (float4) 0;
    float4 Accum2 = (float4) 0;

    for (int y = LeftTop.y; y <= RightBottom.y; ++y)
    {
        for (int x = LeftTop.x; x <= RightBottom.x; ++x)
        {
            float3 Color = SampleColor(int2(x, y));
            Accum += float4(Color, 1);
            Accum2 += float4(Color * Color, 1);
        }
    }
    
    Accum.xyz /= Accum.w;
    Accum2.xyz /= Accum2.w;
    float3 Variance = Accum2.xyz - Pow2(Accum.xyz);
    return float4(Accum.xyz, Variance.x + Variance.y + Variance.z);
}

float4 ComputeNormalMeanAndVariance(int2 LeftTop, int2 RightBottom)
{
    float4 Accum = (float4) 0;
    float4 Accum2 = (float4) 0;
    
    for (int y = LeftTop.y; y <= RightBottom.y; ++y)
    {
        for (int x = LeftTop.x; x <= RightBottom.x; ++x)
        {
            float4 Normal = SampleNormal(int2(x, y));
            Accum += Normal;
            Accum2 += Normal * Normal;
        }
    }
    
    if (Accum.w > 0)
    {
        Accum.xyz /= Accum.w;
        Accum2.xyz /= Accum2.w;
        float3 Variance = Accum2.xyz - Pow2(Accum.xyz);
        return float4(normalize(Accum.xyz), Variance.x + Variance.y + Variance.z);
    }
    else
    {
        return float4(0, 0, 0, 0);
    }
}

float4 ComputeMeanAndVariance(int2 LeftTop, int2 RightBottom)
{
#if TARGET_TYPE == TARGET_TYPE_COLOR
    return ComputeColorMeanAndVariance(LeftTop, RightBottom);
#elif TARGET_TYPE == TARGET_TYPE_NORMAL
    return ComputeNormalMeanAndVariance(LeftTop, RightBottom);
#endif
}

float3 ClassicKuwaharaFilter(int2 PixelPos)
{
    int2 LeftTop = ClampToViewport(PixelPos - FilterSize);
    int2 RightBottom = ClampToViewport(PixelPos + FilterSize);
    
    float4 MeanAndMinVariance = ComputeMeanAndVariance(LeftTop, PixelPos);
    
    float4 MeanAndVariance = ComputeMeanAndVariance(int2(PixelPos.x, LeftTop.y), int2(RightBottom.x, PixelPos.y));
    if (MeanAndVariance.w < MeanAndMinVariance.w)
    {
        MeanAndMinVariance = MeanAndVariance;
    }
    
    MeanAndVariance = ComputeMeanAndVariance(int2(LeftTop.x, PixelPos.y), int2(PixelPos.x, RightBottom.y));
    if (MeanAndVariance.w < MeanAndMinVariance.w)
    {
        MeanAndMinVariance = MeanAndVariance;
    }
    
    MeanAndVariance = ComputeMeanAndVariance(PixelPos, RightBottom);
    if (MeanAndVariance.w < MeanAndMinVariance.w)
    {
        MeanAndMinVariance = MeanAndVariance;
    }
    
#if TARGET_TYPE == TARGET_TYPE_COLOR
    return MeanAndMinVariance.xyz;
#elif TARGET_TYPE == TARGET_TYPE_NORMAL
    return any(MeanAndMinVariance.xyz) ? 0.5 * normalize(MeanAndMinVariance.xyz) + 0.5 : float3(0, 0, 0);
#endif
}

float GaussianWeight(float2 V)
{
    return exp(-dot(V, V) / float(FilterSize * FilterSize));
}

float ComputeAlpha(float Variance)
{
    return 1.0 / (1.0 + 1000000.0 * Variance);
}

float4 ComputeColorMeanAndAlpha(int2 LeftTop, int2 RightBottom, int2 CenterPos)
{
    float4 Accum = (float4) 0;
    float4 Accum2 = (float4) 0;

    for (int y = LeftTop.y; y <= RightBottom.y; ++y)
    {
        for (int x = LeftTop.x; x <= RightBottom.x; ++x)
        {
            float W = GaussianWeight(int2(x, y) - CenterPos);
            float3 Color = SampleColor(int2(x, y));
            Accum += float4(W * Color, W);
            Accum2 += float4(W * Color * Color, W);
        }
    }
    
    Accum.xyz /= Accum.w;
    Accum2.xyz /= Accum2.w;
    float3 Variance = Accum2.xyz - Pow2(Accum.xyz);
    float Alpha = ComputeAlpha(Variance.x + Variance.y + Variance.z);
    return float4(Alpha * Accum.xyz, Alpha);
}

float4 ComputeNormalMeanAndAlpha(int2 LeftTop, int2 RightBottom, int2 CenterPos)
{
    float4 Accum = (float4) 0;
    float4 Accum2 = (float4) 0;
    
    for (int y = LeftTop.y; y <= RightBottom.y; ++y)
    {
        for (int x = LeftTop.x; x <= RightBottom.x; ++x)
        {
            float W = GaussianWeight(int2(x, y) - CenterPos);
            float4 Normal = SampleNormal(int2(x, y));
            Accum += W * Normal;
            Accum2 += W * Normal * Normal;
        }
    }
    
    if (Accum.w > 0)
    {
        Accum.xyz /= Accum.w;
        Accum2.xyz /= Accum2.w;
        float3 Variance = Accum2.xyz - Pow2(Accum.xyz);
        float Alpha = ComputeAlpha(Variance.x + Variance.y + Variance.z);
        return float4(Alpha * normalize(Accum.xyz), Alpha);
    }
    else
    {
        return float4(0, 0, 0, 1);
    }
}

float4 ComputeMeanAndAlpha(int2 LeftTop, int2 RightBottom, int2 CenterPos)
{
#if TARGET_TYPE == TARGET_TYPE_COLOR
    return ComputeColorMeanAndAlpha(LeftTop, RightBottom, CenterPos);
#elif TARGET_TYPE == TARGET_TYPE_NORMAL
    return ComputeNormalMeanAndAlpha(LeftTop, RightBottom, CenterPos);
#endif
}

float3 GeneralizedKuwaharaFilter(int2 PixelPos)
{
    int2 LeftTop = ClampToViewport(PixelPos - FilterSize);
    int2 RightBottom = ClampToViewport(PixelPos + FilterSize);
    
    float4 Accum = (float4) 0;
    Accum += ComputeMeanAndAlpha(LeftTop, PixelPos, PixelPos);
    Accum += ComputeMeanAndAlpha(int2(PixelPos.x, LeftTop.y), int2(RightBottom.x, PixelPos.y), PixelPos);
    Accum += ComputeMeanAndAlpha(int2(LeftTop.x, PixelPos.y), int2(PixelPos.x, RightBottom.y), PixelPos);
    Accum += ComputeMeanAndAlpha(PixelPos, RightBottom, PixelPos);
    
#if TARGET_TYPE == TARGET_TYPE_COLOR
    return Accum.xyz / Accum.w;
#elif TARGET_TYPE == TARGET_TYPE_NORMAL
    return any(Accum.xyz) ? 0.5 * normalize(Accum.xyz) + 0.5 : float3(0, 0, 0);
#endif
}

float3 SampleOrientationByColor(int2 PixelPos)
{
    return OrientationTexture[ClampToViewport(PixelPos)].xyz;
}

float SampleOrientationByDepth(int2 PixelPos)
{
    return OrientationTexture[ClampToViewport(PixelPos)].x;
}

void ComputeOrientationAndAnisotropy(int2 PixelPos, out float CosPhi, out float SinPhi, out float A)
{
    float E = 0, G = 0, F = 0;
#if ORIENTATION == ORIENTTATION_COLOR
    float3 Fx = SampleOrientationByColor(PixelPos + int2(+1, 0)) - SampleOrientationByColor(PixelPos + int2(-1, 0));
    float3 Fy = SampleOrientationByColor(PixelPos + int2(0, +1)) - SampleOrientationByColor(PixelPos + int2(0, -1));
    E = dot(Fx, Fx);
    G = dot(Fy, Fy);
    F = dot(Fx, Fy);
#elif ORIENTATION == ORIENTTATION_DEPTH
    float Fx = SampleOrientationByDepth(PixelPos + int2(+1, 0)) - SampleOrientationByDepth(PixelPos + int2(-1, 0));
    float Fy = SampleOrientationByDepth(PixelPos + int2(0, +1)) - SampleOrientationByDepth(PixelPos + int2(0, -1));
    E = Fx * Fx;
    G = Fy * Fy;
    F = Fx * Fy;
#endif
    
    float D = sqrt(Pow2(E - G) + 4.0 * F * F);
    float L1 = 0.5 * (E + G + D);
    float L2 = 0.5 * (E + G - D);
    float2 t = float2(L1 - E, -F);
    t = any(t) ? normalize(t) : float2(0.0, -1.0);
    
    CosPhi = t.x;
    SinPhi = -t.y;
    A = (L1 + L2) > 0.0 ? (L1 - L2) / (L1 + L2) : 0.0;    
}

int GetSubregionIndex(float2 V)
{
    if (abs(V.x) > abs(V.y))
    {
        return V.x > 0.0 ? 0 : 2;
    }
    else
    {
        return V.y > 0 ? 1 : 3;
    }
}

float3 AnisotropyKuwaharaFilter(int2 PixelPos)
{
    float CosPhi, SinPhi, A;
    ComputeOrientationAndAnisotropy(PixelPos, CosPhi, SinPhi, A);
    
    float a = float(FilterSize) * (1.0 + A) / 1.0;
    float b = float(FilterSize) * 1.0 / (1.0 + A);
    float2x2 SR = mul(float2x2(1.0 / a, 0, 1.0 / b, 0), float2x2(CosPhi, -SinPhi, SinPhi, CosPhi));
    
    float4 SubAccum[4] = { (float4) 0, (float4) 0, (float4) 0, (float4) 0 };
    float4 SubAccum2[4] = { (float4) 0, (float4) 0, (float4) 0, (float4) 0 };
    
    int MaxX = a * abs(CosPhi) + b * abs(SinPhi);
    int MaxY = a * abs(SinPhi) + b * abs(CosPhi);
    for (int y = -MaxY; y <= MaxY; ++y)
    {
        for (int x = -MaxX; x <= MaxX; ++x)
        {
            float2 v = mul(SR, float2(x, y));
            if (dot(v, v) <= 1.0)
            {
                int Index = GetSubregionIndex(int2(x, y));
#if TARGET_TYPE == TARGET_TYPE_COLOR
                float3 Color = SampleColor(ClampToViewport(PixelPos + int2(x, y)));
                SubAccum[Index] += float4(Color, 1);
                SubAccum2[Index] += float4(Color * Color, 1);
#elif TARGET_TYPE == TARGET_TYPE_NORMAL
                float4 Normal = SampleNormal(ClampToViewport(PixelPos + int2(x, y)));
                SubAccum[Index] += Normal;
                SubAccum2[Index] += Normal * Normal;
#endif
            }
        }
    }
    
    float4 Accum = (float4) 0;
    
    for (int i = 0; i < 4; ++i)
    {
        if (SubAccum[i].w != 0.0)
        {
            SubAccum[i].xyz /= SubAccum[i].w;
            SubAccum2[i].xyz /= SubAccum2[i].w;
            float3 Variance = SubAccum2[i].xyz - Pow2(SubAccum[i].xyz);
            float Alpha = 1.0 / (1.0 + 1000000.0 * (Variance.x + Variance.y + Variance.z));
            Accum += float4(Alpha * SubAccum[i].xyz, Alpha);
        }
    }
    
#if TARGET_TYPE == TARGET_TYPE_COLOR
    return Accum.xyz / Accum.w;
#elif TARGET_TYPE == TARGET_TYPE_NORMAL
    return any(Accum.xyz) ? 0.5 * normalize(Accum.xyz) + 0.5 : float3(0, 0, 0);
#endif
}

float3 SymmetricColorSample(int2 PixelPos, int2 Offset, float3 Center)
{
    float3 Value1 = SampleColor(ClampToViewport(PixelPos - Offset));
    float3 Value2 = SampleColor(ClampToViewport(PixelPos + Offset));
    float3 Delta1 = Value1 - Center;
    float3 Delta2 = Value2 - Center;
    float3 Value = dot(Delta1, Delta1) < dot(Delta2, Delta2) ? Value1 : Value2;
    return Value;
}

float3 SymmetricNormalSample(int2 PixelPos, int2 Offset, float4 Center)
{
    float4 Value1 = SampleNormal(ClampToViewport(PixelPos - Offset));
    float4 Value2 = SampleNormal(ClampToViewport(PixelPos + Offset));
    if (Value1.w && Value2.w)
    {
        float Delta1 = dot(Center.xyz, Value1.xyz);
        float Delta2 = dot(Center.xyz, Value2.xyz);
        return Delta1 < Delta2 ? Value1.xyz : Value2.xyz;
    }
    else if (Value1.w)
    {
        return Value1.xyz;
    }
    else if (Value2.w)
    {
        return Value2.xyz;
    }
    else
    {
        return float3(0, 0, 0);
    }
}

#if TARGET_TYPE == TARGET_TYPE_COLOR
float3 SymmetricSample(int2 PixelPos, int2 Offset, float3 Center)
{
    return SymmetricColorSample(PixelPos, Offset, Center);
}
#elif TARGET_TYPE == TARGET_TYPE_NORMAL
float3 SymmetricSample(int2 PixelPos, int2 Offset, float4 Center)
{
    return SymmetricNormalSample(PixelPos, Offset, Center);
}
#endif

float3 SymmetricNearestNeighborFilter(int2 PixelPos)
{
#if TARGET_TYPE == TARGET_TYPE_COLOR
    float3 Center = SampleColor(PixelPos);
#elif TARGET_TYPE == TARGET_TYPE_NORMAL
    float4 Center = SampleNormal(PixelPos);
    if(Center.a == 0.0)
    {
        return float3(0, 0, 0);
    }
#endif
    
    float4 Accum = float4(Center.xyz, 1.0);
    
    for (int y = -FilterSize; y < 0; ++y)
    {
        for (int x = -FilterSize; x <= FilterSize; ++x)
        {
            Accum += float4(SymmetricSample(PixelPos, int2(x, y), Center), 1);
        }
    }
    
    for (int x = -FilterSize; x < 0; ++x)
    {
        Accum += float4(SymmetricSample(PixelPos, int2(x, 0), Center), 1);
    }
    
#if TARGET_TYPE == TARGET_TYPE_COLOR
    return Accum.xyz / Accum.w;
#elif TARGET_TYPE == TARGET_TYPE_NORMAL
    return any(Accum.xyw) ? 0.5 * normalize(Accum.xyz) + 0.5 : float3(0, 0, 0);
#endif
}

void SketchFilterPS(in float4 SvPosition : SV_Position, out float4 OutColor : SV_Target0)
{
    int2 PixelPos = int2(SvPosition.xy);

#if FILTER_METHOD == FILTER_METHOD_CLASSIC_KUWAHARA
    OutColor = float4(ClassicKuwaharaFilter(PixelPos), 0);
#elif FILTER_METHOD == FILTER_METHOD_GENERALIZED_KUWAHARA
    OutColor = float4(GeneralizedKuwaharaFilter(PixelPos), 0);
#elif FILTER_METHOD == FILTER_METHOD_ANISOTROPIC_KUWAHARA
    OutColor = float4(AnisotropyKuwaharaFilter(PixelPos), 0);
#elif FILTER_METHOD == FILTER_METHOD_SYMMETRIC_NEAREST_NEIGHBOR
    OutColor = float4(SymmetricNearestNeighborFilter(PixelPos), 0);
#endif
}
