/*=============================================================================
	PostProcessLine.usf: PostProcessing Line
=============================================================================*/

#include "/Engine/Private/Common.ush"
#include "/Engine/Private/ScreenPass.ush"
#include "/Engine/Private/DeferredShadingCommon.ush"
#include "/Engine/Private/PostProcessCommon.ush"
#include "/Engine/Private/ColorSpace.ush"

#define FILTER_TYPE_KUWAHARA 0
#define FILTER_TYPE_SNN 1
#define FILTER_TARGET_SCENECOLOR 0
#define FILTER_TARGET_LIGHTING 1

int FilterSize;
int FilterType;
int FilterTarget;
int DebugFilter;

SCREEN_PASS_TEXTURE_VIEWPORT(Input)

Texture2D SceneColorTexture;
// Texture2D SceneDepthTexture;
Texture2D BaseColorTexture;

float Luminance2(float3 Color)
{
    return Pow2(Luminance(Color));
}

float4 ColorAndLuminance2(float3 Color)
{
    return float4(Color, Luminance2(Color));
}

float3 SampleSceneColor(int2 PixelPos)
{
    int2 SamplePos = clamp(PixelPos, int2(0, 0), Input_ViewportMax - 1);
    return SceneColorTexture[SamplePos].rgb;
}

float4 SampleSceneColorAndLuminance2(int2 PixelPos)
{
    int2 SamplePos = clamp(PixelPos, int2(0, 0), Input_ViewportMax - 1);
    return ColorAndLuminance2(SceneColorTexture[SamplePos].rgb);
}

float SampleSceneDepth(int2 PixelPos)
{
    int2 SamplePos = clamp(PixelPos, int2(0, 0), Input_ViewportMax - 1);
    return SceneDepthTexture[SamplePos].x;
}

int SubregionIndex(int2 Pos)
{
    if (Pos.x >= 0)
    {
        return Pos.y >= 0 ? 0 : 3;
    }
    else
    {
        return Pos.y >= 0 ? 1 : 2;
    }
}

float4 AverageColorAndVariance(int2 LeftTop, int2 RightBottom)
{
    float4 ColorAndLum2 = (float4)0;
    
    for (int y = LeftTop.y; y <= RightBottom.y; ++y)
    {
        for (int x = LeftTop.x; x <= RightBottom.x; ++x)
        {
            ColorAndLum2 += SampleSceneColorAndLuminance2(int2(x, y));
        }

    }

    float Area = (RightBottom.x - LeftTop.x + 1) * (RightBottom.y - LeftTop.y + 1);
    ColorAndLum2 /= Area;
    
    return float4(ColorAndLum2.rgb, ColorAndLum2.a - Luminance2(ColorAndLum2.rgb));
}

float3 ClassicKuwaharaFilter(int2 PixelPos)
{
    float4 ColorAndMinVariance = AverageColorAndVariance(PixelPos + int2(-FilterSize, -FilterSize), PixelPos);
    
    float4 ColorAndVariance = AverageColorAndVariance(PixelPos + int2(0, -FilterSize), PixelPos + int2(FilterSize, 0));
    if (ColorAndVariance.a < ColorAndMinVariance.a)
    {
        ColorAndMinVariance = ColorAndVariance;
    }
    
    ColorAndVariance = AverageColorAndVariance(PixelPos + int2(-FilterSize, 0), PixelPos + int2(0, FilterSize));
    if (ColorAndVariance.a < ColorAndMinVariance.a)
    {
        ColorAndMinVariance = ColorAndVariance;
    }
    
    ColorAndVariance = AverageColorAndVariance(PixelPos, PixelPos + int2(FilterSize, FilterSize));
    if (ColorAndVariance.a < ColorAndMinVariance.a)
    {
        ColorAndMinVariance = ColorAndVariance;
    }
    
    return ColorAndMinVariance.rgb;
}

float3 SmoothKuwaharaFilter(int2 PixelPos)
{
    float4 ColorAndAlpha = (float4) 0;
    float4 ColorAndVariance = (float4) 0;
    float Alpha = 0;
    
    ColorAndVariance = AverageColorAndVariance(PixelPos + int2(-FilterSize, -FilterSize), PixelPos);
    Alpha = 1.0 / (1.0 + 1000000.0 * ColorAndVariance.a);
    ColorAndAlpha += float4(Alpha * ColorAndVariance.rgb, Alpha);
    
    ColorAndVariance = AverageColorAndVariance(PixelPos + int2(0, -FilterSize), PixelPos + int2(FilterSize, 0));
    Alpha = 1.0 / (1.0 + 1000000.0 * ColorAndVariance.a);
    ColorAndAlpha += float4(Alpha * ColorAndVariance.rgb, Alpha);
    
    ColorAndVariance = AverageColorAndVariance(PixelPos + int2(-FilterSize, 0), PixelPos + int2(0, FilterSize));
    Alpha = 1.0 / (1.0 + 1000000.0 * ColorAndVariance.a);
    ColorAndAlpha += float4(Alpha * ColorAndVariance.rgb, Alpha);
    
    ColorAndVariance = AverageColorAndVariance(PixelPos, PixelPos + int2(FilterSize, FilterSize));
    Alpha = 1.0 / (1.0 + 1000000.0 * ColorAndVariance.a);
    ColorAndAlpha += float4(Alpha * ColorAndVariance.rgb, Alpha);
    
    return ColorAndAlpha.rgb / ColorAndAlpha.a;
}

float3 ComputeStructureTensorBySceneColor(int2 PixelPos)
{
    float Fx = SampleSceneColorAndLuminance2(PixelPos + int2(+1, 0)).a - SampleSceneColorAndLuminance2(PixelPos + int2(-1, 0)).a;
    float Fy = SampleSceneColorAndLuminance2(PixelPos + int2(0, +1)).a - SampleSceneColorAndLuminance2(PixelPos + int2(0, -1)).a;
    return float3(Fx * Fx, Fy * Fy, Fx * Fy);
}

float3 ComputeStructureTensorBySceneDepth(int2 PixelPos)
{
    float Fx = SampleSceneDepth(PixelPos + int2(+1, 0)) - SampleSceneDepth(PixelPos + int2(-1, 0));
    float Fy = SampleSceneDepth(PixelPos + int2(0, +1)) - SampleSceneDepth(PixelPos + int2(0, -1));
    return float3(Fx * Fx, Fy * Fy, Fx * Fy);    
}

void ComputeOrientationAndAnisotropy(float E, float G, float F, out float Phi, out float A)
{
    float D = sqrt(Pow2(E - G) + 4.0 * F * F);
    float L1 = 0.5 * (E + G + D);
    float L2 = 0.5 * (E + G - D);
    float2 t = float2(L1 - E, -F);
    t = dot(t, t) > 0.0 ? t : float2(0.0, 1.0);
    
    Phi = -atan2(t.y, t.x);
    A = (L1 + L2) > 0.0 ? (L1 - L2) / (L1 + L2) : 0.0;
}

int AnisotropicSubregionIndex(float2 V)
{
    if (abs(V.x) > abs(V.y))
    {
        return V.x > 0.0 ? 0 : 2;
    }
    else
    {
        return V.y > 0 ? 1 : 3;
    }
}

float3 AnisotropicKuwaharaFilter(int2 PixelPos)
{
    float3 StructureTensor = ComputeStructureTensorBySceneColor(PixelPos);
    
    float Phi, A;
    ComputeOrientationAndAnisotropy(StructureTensor.x, StructureTensor.y, StructureTensor.z, Phi, A);
    
    float CosPhi = cos(Phi);
    float SinPhi = sin(Phi);
    float a = float(FilterSize) * (1.0 + A) / 1.0;
    float b = float(FilterSize) * 1.0 / (1.0 + A);
    float Sx = 1.0 / a;
    float Sy = 1.0 / b;
    
    float4 Colors[4] = { (float4) 0, (float4) 0, (float4) 0, (float4) 0 };
    float Weights[4] = { 0, 0, 0, 0 };
    
    int MaxX = sqrt(a * a * CosPhi * CosPhi + b * b * SinPhi * SinPhi);
    int MaxY = sqrt(a * a * SinPhi * SinPhi + b * b * CosPhi * CosPhi);
    for (int y = -MaxY; y <= MaxY; ++y)
    {
        for (int x = -MaxX; x <= MaxX; ++x)
        {
            float2 v = float2(Sx * (x * CosPhi - y * SinPhi), Sy * (x * SinPhi + y * CosPhi));
            if (dot(v, v) <= 1.0)
            {
                int Index = AnisotropicSubregionIndex(int2(x, y));
                float Weight = 1.0;
                Colors[Index] += Weight * SampleSceneColorAndLuminance2(PixelPos + int2(x, y));
                Weights[Index] += Weight;
            }
        }
    }
    
    float4 OutColor = (float4) 0;
    
    for (int i = 0; i < 4; ++i)
    {
        Colors[i] /= Weights[i];
        float Variance2 = Colors[i].a - Luminance2(Colors[i].rgb);
        float Alpha = 1.0 / (1.0 + 1000000.0 * Variance2);
        OutColor += float4(Alpha * Colors[i].rgb, Alpha);
    }

    OutColor.rgb /= OutColor.a;
    return OutColor.rgb;
}

float3 SymmetricSample(int2 PixelPos, int2 Offset, float3 Center)
{
    float3 ColorA = SampleSceneColor(PixelPos - Offset);
    float3 ColorB = SampleSceneColor(PixelPos + Offset);
    float3 DeltaA = ColorA - Center;
    float3 DeltaB = ColorB - Center;
    return dot(DeltaA, DeltaA) < dot(DeltaB, DeltaB) ? ColorA : ColorB;
}

float3 SymmetricNearestNeighborFilter(int2 PixelPos)
{
    float3 Center = SampleSceneColor(PixelPos);
    float4 ColorAndWeight = float4(Center, 1);
    
    for (int y = -FilterSize; y < 0; ++y)
    {
        for (int x = -FilterSize; x <= FilterSize; ++x)
        {
            ColorAndWeight += float4(SymmetricSample(PixelPos, int2(x, y), Center), 1.0);
        }
    }
    
    for (int x = -FilterSize; x < 0; ++x)
    {
        ColorAndWeight += float4(SymmetricSample(PixelPos, int2(x, 0), Center), 1.0);
    }
	
    return ColorAndWeight.rgb / ColorAndWeight.a;
}

void SceneColorKuwaharaFilterPS(in float4 SvPosition: SV_Position, out float4 OutColor: SV_Target0)
{
    int2 PixelPos = int2(SvPosition.xy);
    // OutColor = float4(AnisotropicKuwaharaFilter(PixelPos), 0.0);
    OutColor = float4(SymmetricNearestNeighborFilter(PixelPos), 0.0);

}
