/*=============================================================================
	PostProcessLine.usf: PostProcessing Line
=============================================================================*/

#include "/Engine/Private/Common.ush"
#include "/Engine/Private/ScreenPass.ush"
#include "/Engine/Private/DeferredShadingCommon.ush"
#include "/Engine/Private/PostProcessCommon.ush"
#include "/Engine/Private/ColorSpace.ush"

#define FILTER_TYPE_KUWAHARA 0
#define FILTER_TYPE_SNN 1
#define FILTER_TARGET_SCENECOLOR 0
#define FILTER_TARGET_LIGHTING 1

int FilterSize;
int FilterType;
int FilterTarget;
int DebugFilter;

SCREEN_PASS_TEXTURE_VIEWPORT(Input)

Texture2D SceneColorTexture;
// Texture2D SceneDepthTexture;
Texture2D BaseColorTexture;
Texture2D WorldNormalTexture;
Texture2D InputTexture;
Texture2D OrientationTexture;

float Luminance2(float3 Color)
{
    return Pow2(Luminance(Color));
}

float4 ColorAndLuminance2(float3 Color)
{
    return float4(Color, Luminance2(Color));
}

float3 SampleSceneColor(int2 PixelPos)
{
    int2 SamplePos = clamp(PixelPos, int2(0, 0), Input_ViewportMax - 1);
    return SceneColorTexture[SamplePos].rgb;
}

float4 SampleSceneColorAndLuminance2(int2 PixelPos)
{
    int2 SamplePos = clamp(PixelPos, int2(0, 0), Input_ViewportMax - 1);
    return ColorAndLuminance2(SceneColorTexture[SamplePos].rgb);
}

float4 SampleInputColor(int2 PixelPos)
{
    int2 SamplePos = clamp(PixelPos, int2(0, 0), Input_ViewportMax - 1);
    float3 Color = InputTexture[SamplePos].rgb;
    return float4(Color, Luminance2(Color));
}

float SampleSceneDepth(int2 PixelPos)
{
    int2 SamplePos = clamp(PixelPos, int2(0, 0), Input_ViewportMax - 1);
    return SceneDepthTexture[SamplePos].x;
}

float4 ComputeMeanAndVariance(int2 LeftTop, int2 RightBottom)
{
    float4 ColorAndLum2 = (float4)0;
    
    for (int y = LeftTop.y; y <= RightBottom.y; ++y)
    {
        for (int x = LeftTop.x; x <= RightBottom.x; ++x)
        {
            ColorAndLum2 += SampleInputColor(int2(x, y));
        }

    }

    float Area = (RightBottom.x - LeftTop.x + 1) * (RightBottom.y - LeftTop.y + 1);
    ColorAndLum2 /= Area;
    
    return float4(ColorAndLum2.rgb, ColorAndLum2.a - Luminance2(ColorAndLum2.rgb));
}

float3 ClassicKuwaharaFilter(int2 PixelPos)
{
    float4 ColorAndMinVariance = ComputeMeanAndVariance(PixelPos + int2(-FilterSize, -FilterSize), PixelPos);
    
    float4 ColorAndVariance = ComputeMeanAndVariance(PixelPos + int2(0, -FilterSize), PixelPos + int2(FilterSize, 0));
    if (ColorAndVariance.a < ColorAndMinVariance.a)
    {
        ColorAndMinVariance = ColorAndVariance;
    }
    
    ColorAndVariance = ComputeMeanAndVariance(PixelPos + int2(-FilterSize, 0), PixelPos + int2(0, FilterSize));
    if (ColorAndVariance.a < ColorAndMinVariance.a)
    {
        ColorAndMinVariance = ColorAndVariance;
    }
    
    ColorAndVariance = ComputeMeanAndVariance(PixelPos, PixelPos + int2(FilterSize, FilterSize));
    if (ColorAndVariance.a < ColorAndMinVariance.a)
    {
        ColorAndMinVariance = ColorAndVariance;
    }
    
    return ColorAndMinVariance.rgb;
}

float3 SmoothKuwaharaFilter(int2 PixelPos)
{
    float4 ColorAndAlpha = (float4) 0;
    float4 ColorAndVariance = (float4) 0;
    float Alpha = 0;
    
    ColorAndVariance = ComputeMeanAndVariance(PixelPos + int2(-FilterSize, -FilterSize), PixelPos);
    Alpha = 1.0 / (1.0 + 1000000.0 * ColorAndVariance.a);
    ColorAndAlpha += float4(Alpha * ColorAndVariance.rgb, Alpha);
    
    ColorAndVariance = ComputeMeanAndVariance(PixelPos + int2(0, -FilterSize), PixelPos + int2(FilterSize, 0));
    Alpha = 1.0 / (1.0 + 1000000.0 * ColorAndVariance.a);
    ColorAndAlpha += float4(Alpha * ColorAndVariance.rgb, Alpha);
    
    ColorAndVariance = ComputeMeanAndVariance(PixelPos + int2(-FilterSize, 0), PixelPos + int2(0, FilterSize));
    Alpha = 1.0 / (1.0 + 1000000.0 * ColorAndVariance.a);
    ColorAndAlpha += float4(Alpha * ColorAndVariance.rgb, Alpha);
    
    ColorAndVariance = ComputeMeanAndVariance(PixelPos, PixelPos + int2(FilterSize, FilterSize));
    Alpha = 1.0 / (1.0 + 1000000.0 * ColorAndVariance.a);
    ColorAndAlpha += float4(Alpha * ColorAndVariance.rgb, Alpha);
    
    return ColorAndAlpha.rgb / ColorAndAlpha.a;
}

void ComputeOrientationAndAnisotropy(int2 PixelPos, out float CosPhi, out float SinPhi, out float A)
{
    float E, G, F;
#if 1
    float3 Fx = SampleSceneColor(PixelPos + int2(+1, 0)) - SampleSceneColor(PixelPos + int2(-1, 0));
    float3 Fy = SampleSceneColor(PixelPos + int2(0, +1)) - SampleSceneColor(PixelPos + int2(0, -1));
    E = dot(Fx, Fx);
    G = dot(Fy, Fy);
    F = dot(Fx, Fy);
#else
    float Fx = SampleSceneDepth(PixelPos + int2(+1, 0)) - SampleSceneDepth(PixelPos + int2(-1, 0));
    float Fy = SampleSceneDepth(PixelPos + int2(0, +1)) - SampleSceneDepth(PixelPos + int2(0, -1));
    E = Fx * Fx;
    G = Fy * Fy;
    F = Fx * Fy;
#endif
    
    float D = sqrt(Pow2(E - G) + 4.0 * F * F);
    float L1 = 0.5 * (E + G + D);
    float L2 = 0.5 * (E + G - D);
    float2 t = float2(L1 - E, -F);
    t = dot(t, t) > 0.0 ? normalize(t) : float2(0.0, -1.0);
    
    CosPhi = t.x;
    SinPhi = -t.y;
    A = (L1 + L2) > 0.0 ? (L1 - L2) / (L1 + L2) : 0.0;
}

void ComputeOrientationAndAnisotropyByNormal(int2 PixelPos, out float CosPhi, out float SinPhi, out float A)
{
    float3 Normal = WorldNormalTexture[PixelPos].xyz;
    if (dot(Normal, Normal) == 0)
    {
        CosPhi = 0.0;
        SinPhi = -1.0;
        A = 0.0;
        return;
    }

    Normal = 2.0 * Normal - 1;
    Normal = mul(Normal, (float3x3)View.TranslatedWorldToClip);

    if (dot(Normal.xy, Normal.xy) == 0.0)
    {
        CosPhi = 0.0;
        SinPhi = -1.0;
        A = 0.0;
    }
    else
    {
        Normal.xy = normalize(Normal.xy);
        CosPhi = Normal.x;
        SinPhi = -Normal.y;
        A = abs(Normal.z);
    }
}

int GetSubregionIndex(float2 V)
{
    if (abs(V.x) > abs(V.y))
    {
        return V.x > 0.0 ? 0 : 2;
    }
    else
    {
        return V.y > 0 ? 1 : 3;
    }
}

float4 GetWeights(float2 V)
{
    if (dot(V, V) == 0)
    {
        return float4(1, 1, 1, 1);
    }
    else
    {
        V = normalize(V);
        return saturate(float4(
            dot(V, float2(+1, 0)),
            dot(V, float2(0, +1)),
            dot(V, float2(-1, 0)),
            dot(V, float2(0, -1))));
    }
}

float3 AnisotropicKuwaharaFilter(int2 PixelPos)
{
    float CosPhi, SinPhi, A;
    ComputeOrientationAndAnisotropy(PixelPos, CosPhi, SinPhi, A);
    
    float a = float(FilterSize) * (1.0 + A) / 1.0;
    float b = float(FilterSize) * 1.0 / (1.0 + A);
    float2x2 SR = mul(float2x2(1.0 / a, 0, 1.0 / b, 0), float2x2(CosPhi, -SinPhi, SinPhi, CosPhi));
    
    float4 Colors[4] = { (float4) 0, (float4) 0, (float4) 0, (float4) 0 };
    float Weights[4] = { 0, 0, 0, 0 };
    
    int MaxX = ceil(a * abs(CosPhi) + b * abs(SinPhi));
    int MaxY = ceil(a * abs(SinPhi) + b * abs(CosPhi));
    for (int y = -MaxY; y <= MaxY; ++y)
    {
        for (int x = -MaxX; x <= MaxX; ++x)
        {
            float2 v = mul(SR, float2(x, y));
            if (dot(v, v) <= 1.0)
            {
                int Index = GetSubregionIndex(int2(x, y));
                Colors[Index] += SampleSceneColorAndLuminance2(PixelPos + int2(x, y));
                Weights[Index] += 1.0;
            }
        }
    }
    
    float4 OutColor = (float4) 0;
    
    for (int i = 0; i < 4; ++i)
    {
        if (Weights[i] != 0.0)
        {
            Colors[i] /= Weights[i];
            float Variance2 = Colors[i].a - Luminance2(Colors[i].rgb);
            float Alpha = 1.0 / (1.0 + 1000000.0 * Variance2);
            OutColor += float4(Alpha * Colors[i].rgb, Alpha);
        }
    }

    OutColor.rgb /= OutColor.a;
    return OutColor.rgb;
}

float3 SymmetricSample(int2 PixelPos, int2 Offset, float3 Center)
{
    float3 ColorA = SampleSceneColor(PixelPos - Offset);
    float3 ColorB = SampleSceneColor(PixelPos + Offset);
    float3 DeltaA = ColorA - Center;
    float3 DeltaB = ColorB - Center;
    return dot(DeltaA, DeltaA) < dot(DeltaB, DeltaB) ? ColorA : ColorB;
}

float3 SymmetricNearestNeighborFilter(int2 PixelPos)
{
    float3 Center = SampleSceneColor(PixelPos);
    float4 ColorAndWeight = float4(Center, 1);
    
    for (int y = -FilterSize; y < 0; ++y)
    {
        for (int x = -FilterSize; x <= FilterSize; ++x)
        {
            ColorAndWeight += float4(SymmetricSample(PixelPos, int2(x, y), Center), 1.0);
        }
    }
    
    for (int x = -FilterSize; x < 0; ++x)
    {
        ColorAndWeight += float4(SymmetricSample(PixelPos, int2(x, 0), Center), 1.0);
    }
	
    return ColorAndWeight.rgb / ColorAndWeight.a;
}

void SceneColorSketchFilterPS(in float4 SvPosition: SV_Position, out float4 OutColor: SV_Target0)
{
    int2 PixelPos = int2(SvPosition.xy);
    OutColor = float4(AnisotropicKuwaharaFilter(PixelPos), 0.0);
    // OutColor = float4(SymmetricNearestNeighborFilter(PixelPos), 0.0);

}

float4 SampleWorldNormal(int2 PixelPos)
{
    int2 SamplePos = clamp(PixelPos, 0, Input_ViewportMax - 1);
    float3 Raw = InputTexture[SamplePos];
    Raw = floor(8.0 * Raw) / 8.0;
    return dot(Raw, Raw) > 0 ? float4(2.0 * Raw - 1.0, 1.0) : float4(0, 0, 0, 0);
}

float4 ComputeNormalMeanAndVariance(int2 LeftTop, int2 RightBottom)
{
    float3 Normal = (float3) 0;
    float3 Normal2 = (float3) 0;
    float Weight = 0.0;
    
    for (int y = LeftTop.y; y <= RightBottom.y; ++y)
    {
        for (int x = LeftTop.x; x <= RightBottom.x; ++x)
        {
            float4 N = SampleWorldNormal(int2(x, y));
            N.xyz *= N.w;
            Normal += N.xyz;
            Normal2 += N.xyz * N.xyz;
            Weight += N.w;
        }

    }
    
    if (dot(Normal, Normal)== 0)
    {
        return float4(0, 0, 0, 0);
    }
    else
    {
        float3 S = Normal2 / Weight - Pow2(Normal / Weight);
        return float4(normalize(Normal), S.x + S.y + S.z);
    }
}

float3 NormalKuwaharaFilter(int2 PixelPos)
{
    float4 NormalAndAlpha = (float4) 0;
    float4 NormalAndVariance = (float4) 0;
    float Alpha = 0;
    
    NormalAndVariance = ComputeNormalMeanAndVariance(PixelPos + int2(-FilterSize, -FilterSize), PixelPos);
    Alpha = 1.0 / (1.0 + 10000.0 * NormalAndVariance.a);
    NormalAndAlpha += float4(Alpha * NormalAndVariance.xyz, Alpha);
    
    NormalAndVariance = ComputeNormalMeanAndVariance(PixelPos + int2(0, -FilterSize), PixelPos + int2(FilterSize, 0));
    Alpha = 1.0 / (1.0 + 10000.0 * NormalAndVariance.a);
    NormalAndAlpha += float4(Alpha * NormalAndVariance.xyz, Alpha);
    
    NormalAndVariance = ComputeNormalMeanAndVariance(PixelPos + int2(-FilterSize, 0), PixelPos + int2(0, FilterSize));
    Alpha = 1.0 / (1.0 + 10000.0 * NormalAndVariance.a);
    NormalAndAlpha += float4(Alpha * NormalAndVariance.xyz, Alpha);
    
    NormalAndVariance = ComputeNormalMeanAndVariance(PixelPos, PixelPos + int2(FilterSize, FilterSize));
    Alpha = 1.0 / (1.0 + 10000.0 * NormalAndVariance.a);
    NormalAndAlpha += float4(Alpha * NormalAndVariance.xyz, Alpha);
    
    if (NormalAndAlpha.w == 0)
    {
        return float3(0, 0, 0);
    }
    else
    {
        return 0.5 * normalize(NormalAndAlpha.xyz) + 0.5 ;
    }
}

void GBufferSketchFilterPS(in float4 SvPosition : SV_Position, out float4 OutColor : SV_Target0)
{
    int2 PixelPos = int2(SvPosition.xy);
    OutColor = float4(NormalKuwaharaFilter(PixelPos).xyz, 0.0);
    // OutColor = float4(AnisotropicKuwaharaFilter(PixelPos), 0.0);
    // OutColor = float4(SymmetricNearestNeighborFilter(PixelPos), 0.0);
}
